version: "3.0"
services:
  db:
    container_name: "DeribitAPI-service"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5440:5432"
    networks:
      - custom
  db_test:
    container_name: "DeribitAPI-service_test"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - volume_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=DeribitAPI_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_PORT=5442
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "5442:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  volume:
  volume_test:
