"""create table

Revision ID: f727f0467920
Revises: 
Create Date: 2023-06-13 20:34:01.401756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f727f0467920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_ticker', sa.String(length=255), nullable=False),
    sa.Column('current_price', sa.String(length=255), nullable=False),
    sa.Column('unix_time', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
